# Generated by Django 2.1.2 on 2019-02-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wines', '0002_auto_20190217_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='points',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
