# Generated by Django 2.1.2 on 2019-02-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wines', '0003_auto_20190217_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='points',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='wine',
            name='price',
            field=models.FloatField(default=-1.0),
        ),
    ]
